# Resmi Nginx temel imajını kullanın
FROM nginx:latest

# Özel HTML dosyasını ekleyin
COPY backend.html /usr/share/nginx/html/backend.html

# Docker içinde çalışacak komutu belirtin
CMD ["nginx", "-g", "daemon off;"]