# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: backend
#   name: backend
#   namespace: product
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - image: ghcr.io/mehmetkanus17/backend:latest
#         name: backend
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: backend
#   name: backend-svc
#   namespace: product
# spec:
#   ports:
#   - port: 80
#     protocol: TCP
#     targetPort: 80
#   selector:
#     app: backend
