  # apiVersion: v1
  # kind: Secret
  # metadata:
  #   name: example-tls
  #   namespace: product
  # data:
  #   tls.crt: <base64 encoded cert>
  #   tls.key: <base64 encoded key>
  # type: kubernetes.io/tls