name: Build error pages images
on:
  push:
    branches:
      - main
env:
  ERROR_IMAGE: ghcr.io/mehmetkanus17/shopping
  REGISTRY: ghcr.io

jobs:
  build-shopping:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: tagging image and metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ${{ env.ERROR_IMAGE }}
          tags: |
            ${{ github.sha }}
            latest

      - name: login GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push image to repository
        uses: int128/kaniko-action@v1
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
